### ISSUE TITLE
{#All} Disparition of navbar logo during navigation

### ISSUE THREAD

**Issue by PierreBrisorgueil** [weareopensource/roMEANet#5]

**Comment by jlebard** [comment]
core/client/views/sidenav.client.view.html
Line 5 : 
 <img src="modules/core/client/img/brand/logo-white.png" width="50px" class="logo" />
to: 
 <img src="/modules/core/client/img/brand/logo-white.png" width="50px" class="logo" />

**Comment by PierreBrisorgueil** [comment]
fix #a909c5b
