### ISSUE TITLE
Integrate APIKEY for all request on /api

### ISSUE THREAD

**Issue by jlebard** [weareopensource/roMEANet#6]
if is possible : add param apikey and get User for continue on api.

**Comment by PierreBrisorgueil** [comment]
we use JWT token, to generate an access token, a first request give the token to the client, can't deal with this ? 

i think apiKey is a specific use case @farhatmo ?

**Comment by jlebard** [comment]
ok, but how ? (it's babar ... for information)

**Comment by jlebard** [comment]
ok so for info : 
POST request on /api/auth/signin with usernameOrEmail and password value
